name: Sync GitLab to GitHub

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily; adjust as needed
  workflow_dispatch:
    inputs:
      event_type:
        required: true
        default: "gitlab_sync"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitLab repository
        env:
          GL_PAT: ${{ secrets.GL_PAT }}
        run: |
          git clone https://oauth2:${GL_PAT}@gitlab.com/Malavisto/scripts.git gitlab-repo
          cd gitlab-repo
          git remote remove origin
          git remote add origin https://Malavisto:${{ secrets.GH_PAT }}@github.com/Malavisto/scripts.git
          
      - name: Set Git Config
        env:
          GIT_EMAIL: ${{ secrets.GH_EMAIL }}
          GIT_NAME: ${{ secrets.GH_NAME }}      
        run: |
          cd gitlab-repo
          git config user.email "${GIT_EMAIL}"
          git config user.name "${GIT_NAME}"
          
      - name: Pull and Push to GitHub
        run: |
          cd gitlab-repo
          git pull origin main --rebase
          git push -u origin main
