name: Sync GitLab to GitHub

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily; adjust as needed
  workflow_dispatch:

jobs:
  sync:
    runs-on: masungulo
    steps:
      - name: Clone GitLab repository
        env:
          GL_PAT: ${{ secrets.GL_PAT }}
        run: |
          git clone https://oauth2:${GL_PAT}@gitlab.com/Malavisto/scripts.git gitlab-repo
          cd gitlab-repo
          git remote remove origin
          git remote add origin https://Malavisto:${{ secrets.GH_PAT }}@github.com/Malavisto/scripts.git

      - name: Pull and Push to GitHub
        run: |
          cd gitlab-repo
          git pull origin main --rebase
          git push -u origin main
